import type { Problem } from "./types";

// Starter vault embedded into the app. Same content as sample-problems/*.json
// (ids left empty so the backend assigns uuids). Used by the welcome flow
// to seed a fresh vault in one click. Import.tsx keeps its own shorter
// SAMPLE for the JSON template.
export const SAMPLE_PROBLEMS: Problem[] = [
  {
    id: "",
    title: "A+B (sanity check)",
    statement_md: "Given two integers A and B on a single line, print their sum.\n\n**Input**\nOne line: `A B` (-10^9 <= A, B <= 10^9)\n\n**Output**\nA single integer: A + B.",
    tags: ["implementation", "warmup"],
    difficulty: 800,
    time_limit_ms: 1000,
    memory_limit_mb: 256,
    source: "self-authored",
    tests: [
      { id: "", input: "2 3\n", expected_output: "5\n" },
      { id: "", input: "-5 10\n", expected_output: "5\n" },
      { id: "", input: "1000000000 1000000000\n", expected_output: "2000000000\n" },
    ],
    brute_force_src: null,
    brute_force_lang: null,
    notes_md: null,
    primary_technique_id: null,
    hints: [],
  },
  {
    id: "",
    title: "Anton and Danik",
    statement_md: "Anton and Danik played n games; none were ties. Given a string of 'A'/'D' recording each game's winner, print `Anton` if Anton won more, `Danik` if Danik won more, or `Friendship` if tied.\n\n**Input**\nLine 1: n (1 <= n <= 100000)\nLine 2: a string of n characters, each 'A' or 'D'\n\n**Output**\n`Anton`, `Danik`, or `Friendship`.",
    tags: ["implementation", "strings", "counting"],
    difficulty: 800,
    time_limit_ms: 1000,
    memory_limit_mb: 256,
    source: "Codeforces 734A (Anton and Danik), restated",
    tests: [
      { id: "", input: "6\nADAAAA\n", expected_output: "Anton\n" },
      { id: "", input: "7\nDDDAADA\n", expected_output: "Danik\n" },
      { id: "", input: "6\nDADADA\n", expected_output: "Friendship\n" },
    ],
    brute_force_src: null,
    brute_force_lang: null,
    notes_md: null,
    primary_technique_id: null,
    hints: [],
  },
  {
    id: "",
    title: "Anton and Letters",
    statement_md: "A set of lowercase letters is written as `{a, b, c}` (comma-space separated, wrapped in curly braces; possibly with duplicates, possibly empty `{}`). Count the distinct letters.\n\n**Input**\nOne line: the set, at most 1000 characters, starting with `{` and ending with `}`.\n\n**Output**\nA single integer: the number of distinct letters.",
    tags: ["strings", "set", "implementation"],
    difficulty: 800,
    time_limit_ms: 1000,
    memory_limit_mb: 256,
    source: "Codeforces 443A (Anton and Letters), restated",
    tests: [
      { id: "", input: "{a, b, c}\n", expected_output: "3\n" },
      { id: "", input: "{b, a, b, a}\n", expected_output: "2\n" },
      { id: "", input: "{}\n", expected_output: "0\n" },
    ],
    brute_force_src: null,
    brute_force_lang: null,
    notes_md: null,
    primary_technique_id: null,
    hints: [],
  },
  {
    id: "",
    title: "Beautiful Matrix",
    statement_md: "You have a 5x5 matrix of 24 zeroes and a single one. You may repeatedly swap two neighboring rows or two neighboring columns. Find the minimum number of swaps to move the one to the center cell (row 3, column 3), 1-indexed.\n\n**Input**\n5 lines of 5 space-separated integers each — the matrix.\n\n**Output**\nA single integer: the minimum number of moves.",
    tags: ["implementation", "matrix", "coordinates"],
    difficulty: 800,
    time_limit_ms: 2000,
    memory_limit_mb: 256,
    source: "Codeforces 263A (Beautiful Matrix), restated",
    tests: [
      { id: "", input: "0 0 0 0 0\n0 0 0 0 1\n0 0 0 0 0\n0 0 0 0 0\n0 0 0 0 0\n", expected_output: "3\n" },
      { id: "", input: "0 0 0 0 0\n0 0 0 0 0\n0 1 0 0 0\n0 0 0 0 0\n0 0 0 0 0\n", expected_output: "1\n" },
    ],
    brute_force_src: null,
    brute_force_lang: null,
    notes_md: null,
    primary_technique_id: null,
    hints: [],
  },
  {
    id: "",
    title: "Boy or Girl",
    statement_md: "Given a username of lowercase Latin letters, count the number of distinct characters. If that count is even, print `CHAT WITH HER!`; if odd, print `IGNORE HIM!`.\n\n**Input**\nOne line: the username, at most 100 lowercase letters.\n\n**Output**\nOne of the two exact phrases above.",
    tags: ["strings", "implementation", "set"],
    difficulty: 800,
    time_limit_ms: 1000,
    memory_limit_mb: 256,
    source: "Codeforces 236A (Boy or Girl), restated",
    tests: [
      { id: "", input: "wjmzbmr\n", expected_output: "CHAT WITH HER!\n" },
      { id: "", input: "xiaodao\n", expected_output: "IGNORE HIM!\n" },
      { id: "", input: "sevenkplus\n", expected_output: "CHAT WITH HER!\n" },
    ],
    brute_force_src: null,
    brute_force_lang: null,
    notes_md: null,
    primary_technique_id: null,
    hints: [],
  },
  {
    id: "",
    title: "Free Cash",
    statement_md: "n customers arrive at a cafe at given times (hour, minute), in chronological order. Find the minimum number of cash desks needed so that every customer arriving at the same exact minute can be served simultaneously.\n\n**Input**\nLine 1: n (1 <= n <= 100000)\nNext n lines: h m (0<=h<=23, 0<=m<=59), chronological\n\n**Output**\nA single integer: the minimum number of desks (the maximum count of customers sharing one arrival minute).",
    tags: ["implementation", "frequency-counting", "simulation"],
    difficulty: 900,
    time_limit_ms: 2000,
    memory_limit_mb: 256,
    source: "Codeforces 237A (Free Cash), restated",
    tests: [
      { id: "", input: "4\n8 0\n8 10\n8 10\n8 45\n", expected_output: "2\n" },
      { id: "", input: "3\n0 12\n10 11\n22 22\n", expected_output: "1\n" },
    ],
    brute_force_src: null,
    brute_force_lang: null,
    notes_md: null,
    primary_technique_id: null,
    hints: [],
  },
  {
    id: "",
    title: "Sorted Sum",
    statement_md: "You're given a sum written as digits 1, 2 and 3 separated by plus signs (e.g. `3+2+1`). Rearrange the summands into non-decreasing order and print the resulting expression.\n\n**Input**\nOne line: the sum, containing only digits 1-3 and `+`, at most 100 characters.\n\n**Output**\nThe rearranged sum with the same digits, sorted, separated by `+`.",
    tags: ["implementation", "sorting", "strings", "greedy"],
    difficulty: 800,
    time_limit_ms: 1000,
    memory_limit_mb: 256,
    source: "Codeforces 339A (Helpful Maths), restated",
    tests: [
      { id: "", input: "3+2+1\n", expected_output: "1+2+3\n" },
      { id: "", input: "1+1+3+1+3\n", expected_output: "1+1+1+3+3\n" },
    ],
    brute_force_src: null,
    brute_force_lang: null,
    notes_md: null,
    primary_technique_id: null,
    hints: [],
  },
  {
    id: "",
    title: "Maximum Subarray Sum",
    statement_md: "Given an array of N integers, find the maximum sum of a contiguous subarray (Kadane's algorithm territory).\n\n**Input**\nLine 1: N\nLine 2: N space-separated integers (each with |a_i| <= 10^9)\n\n**Output**\nA single integer: the maximum subarray sum.",
    tags: ["dp", "arrays"],
    difficulty: 1200,
    time_limit_ms: 1500,
    memory_limit_mb: 256,
    source: "self-authored",
    tests: [
      { id: "", input: "9\n-2 1 -3 4 -1 2 1 -5 4\n", expected_output: "6\n" },
      { id: "", input: "1\n-5\n", expected_output: "-5\n" },
      { id: "", input: "4\n1 2 3 4\n", expected_output: "10\n" },
    ],
    brute_force_src: null,
    brute_force_lang: null,
    notes_md: null,
    primary_technique_id: null,
    hints: [],
  },
  {
    id: "",
    title: "Case-insensitive Compare",
    statement_md: "Given two strings of equal length (uppercase and lowercase Latin letters), compare them lexicographically ignoring case.\n\n**Input**\nLine 1: first string\nLine 2: second string (both length 1-100, same length)\n\n**Output**\n`-1` if the first is smaller, `1` if the second is smaller, `0` if equal (case-insensitive).",
    tags: ["strings", "implementation"],
    difficulty: 800,
    time_limit_ms: 1000,
    memory_limit_mb: 256,
    source: "Codeforces 112A (Petya and Strings), restated",
    tests: [
      { id: "", input: "aaaa\naaaA\n", expected_output: "0\n" },
      { id: "", input: "abs\nAbz\n", expected_output: "-1\n" },
      { id: "", input: "abcdefg\nAbCdEfF\n", expected_output: "1\n" },
    ],
    brute_force_src: null,
    brute_force_lang: null,
    notes_md: null,
    primary_technique_id: null,
    hints: [],
  },
  {
    id: "",
    title: "Smallest k with n | k^n",
    statement_md: "Given a positive integer n, find the smallest positive integer k such that n divides k^n.\n\n**Input**\nOne line: n (1 <= n <= 10^9)\n\n**Output**\nA single integer: the smallest such k.\n\n**Hint (number theory)**: the answer is the product of the distinct prime factors of n.",
    tags: ["math", "number-theory", "prime-factorization"],
    difficulty: 800,
    time_limit_ms: 2000,
    memory_limit_mb: 256,
    source: "Codeforces 2205B (Simons and Cakes for Success), restated — exact numeric constraints self-verified, not scraped",
    tests: [
      { id: "", input: "1\n", expected_output: "1\n" },
      { id: "", input: "2\n", expected_output: "2\n" },
      { id: "", input: "4\n", expected_output: "2\n" },
      { id: "", input: "6\n", expected_output: "6\n" },
      { id: "", input: "12\n", expected_output: "6\n" },
    ],
    brute_force_src: null,
    brute_force_lang: null,
    notes_md: null,
    primary_technique_id: null,
    hints: [],
  },
  {
    id: "",
    title: "Static Range Sum Queries",
    statement_md: "Given an array of n integers, process q queries. Each query gives a range [a,b] (1-indexed, inclusive); report the sum of the array within that range.\n\n**Input**\nLine 1: n q\nLine 2: n integers (the array)\nNext q lines: a b (1 <= a <= b <= n)\n\n**Output**\nq lines, one integer per query: the sum of a[a..b].\n\n**Note**: this is the canonical prefix-sum milestone problem — the one where `pref[b] - pref[a-1]` should become automatic.",
    tags: ["prefix-sum", "arrays"],
    difficulty: 900,
    time_limit_ms: 1000,
    memory_limit_mb: 256,
    source: "CSES-style (Static Range Sum Queries), self-verified by hand",
    tests: [
      { id: "", input: "8 3\n3 2 4 5 1 1 5 3\n2 4\n5 6\n1 8\n", expected_output: "11\n2\n24\n" },
    ],
    brute_force_src: null,
    brute_force_lang: null,
    notes_md: null,
    primary_technique_id: null,
    hints: [],
  },
  {
    id: "",
    title: "Stones on the Table",
    statement_md: "There are n stones in a row, each red (R), green (G), or blue (B). Count the minimum number of stones to remove so that no two neighboring stones share a color.\n\n**Input**\nLine 1: n (1 <= n <= 50)\nLine 2: a string of length n over {R,G,B}\n\n**Output**\nA single integer: the minimum number of stones to remove.",
    tags: ["implementation", "warmup", "strings"],
    difficulty: 800,
    time_limit_ms: 1000,
    memory_limit_mb: 256,
    source: "Codeforces 266A (Stones on the Table), restated",
    tests: [
      { id: "", input: "3\nRRG\n", expected_output: "1\n" },
      { id: "", input: "5\nRRRRR\n", expected_output: "4\n" },
      { id: "", input: "4\nBRBG\n", expected_output: "0\n" },
    ],
    brute_force_src: null,
    brute_force_lang: null,
    notes_md: null,
    primary_technique_id: null,
    hints: [],
  },
  {
    id: "",
    title: "Twins",
    statement_md: "You have n coins of given values. Pick the minimum number of coins so that your sum is strictly greater than the sum of the remaining coins.\n\n**Input**\nLine 1: n (1 <= n <= 100)\nLine 2: n integers, each 1-100 — the coin values\n\n**Output**\nA single integer: the minimum number of coins needed.",
    tags: ["greedy", "sorting"],
    difficulty: 900,
    time_limit_ms: 2000,
    memory_limit_mb: 256,
    source: "Codeforces 160A (Twins), restated",
    tests: [
      { id: "", input: "2\n3 3\n", expected_output: "2\n" },
      { id: "", input: "3\n2 1 2\n", expected_output: "2\n" },
    ],
    brute_force_src: null,
    brute_force_lang: null,
    notes_md: null,
    primary_technique_id: null,
    hints: [],
  },
  {
    id: "",
    title: "Watermelon",
    statement_md: "Given an integer w, determine if it can be split into two positive even integers (they need not be equal).\n\n**Input**\nOne line: w (1 <= w <= 100)\n\n**Output**\n`YES` if possible, `NO` otherwise.",
    tags: ["math", "implementation", "warmup"],
    difficulty: 800,
    time_limit_ms: 1000,
    memory_limit_mb: 256,
    source: "Codeforces 4A (Watermelon), restated",
    tests: [
      { id: "", input: "8\n", expected_output: "YES\n" },
      { id: "", input: "2\n", expected_output: "NO\n" },
      { id: "", input: "3\n", expected_output: "NO\n" },
    ],
    brute_force_src: null,
    brute_force_lang: null,
    notes_md: null,
    primary_technique_id: null,
    hints: [],
  },
  {
    id: "",
    title: "Word",
    statement_md: "Given a word of mixed-case Latin letters, convert it to all-lowercase if lowercase letters are strictly more or equal in count, otherwise to all-uppercase.\n\n**Input**\nOne line: the word, 1-100 letters.\n\n**Output**\nThe converted word.",
    tags: ["strings", "implementation"],
    difficulty: 800,
    time_limit_ms: 2000,
    memory_limit_mb: 256,
    source: "Codeforces 59A (Word), restated",
    tests: [
      { id: "", input: "HoUse\n", expected_output: "house\n" },
      { id: "", input: "ViP\n", expected_output: "VIP\n" },
      { id: "", input: "maTRIx\n", expected_output: "matrix\n" },
    ],
    brute_force_src: null,
    brute_force_lang: null,
    notes_md: null,
    primary_technique_id: null,
    hints: [],
  },
];

// Starter set: created as Learning, reassessed
// in the Techniques tab afterwards.
export const CORE_TECHNIQUES = [
  "Prefix Sum",
  "Two Pointers",
  "Binary Search",
  "Sorting",
  "Greedy",
  "DP Basics",
];
